# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a1536c04f1e49473933e750ca1003a71604dad9eb547412e2becd7c367ad772307b58fa047837211483367c6d78741aad513c3673a72d100b4f4cef4e59090a6

test:
  secret_key_base: 7ddd4a92c4dedc8805ecfc1e5d3cdb3b93ebd73f557b325642eb3869c6690cd837f11ce4f3e2216d01c825d2310403b85d80b85a6058e476a543feaa8b96b182

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
